config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'password_resets/new'

  get 'password_resets/edit'

  get    'help'    =>  'static_pages#help'
  get    'about'   =>  'static_pages#about'
  get    'contact' =>  'static_pages#contact'
  get    'signup'  =>  'users#new'
  get    'login'   =>  'sessions#new'
  post   'login'   =>  'sessions#create'
  delete 'logout'   =>  'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_splash.html.erb
<div class="center jumbotron">
  <%= link_to image_tag('twiiter-logo.png', alt: "Twiiter logo"),
  'http://twiiter.herokuapp.com' %>

  <h2>
    A lightweight Twitter clone, by Augustine Wittkower.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: 'btn btn-lg btn-primary' %>

</div>

<div class="center">
  <%= link_to "Are you an employer? Click me for some helpful info!",
  about_path, class: "btn btn-lg btn-success" %>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>Twiiter</h1>
<h2>Hello!</h2>

<p>
  Thanks for checking out Twiiter. A lightweight Twitter clone built to
  illustrate some of the awesome features that Ruby on Rails is capable of.
</p>
<p>
  It includes examples of:
</p>
<ul>
  <li>Models</li>
  <li>Views</li>
  <li>Controllers</li>
  <li>Partials</li>
  <li>Templates</li>
  <li>Filters</li>
  <li>Validations</li>
  <li>Callbacks</li>
  <li>Has_many/belongs_to and has_many :through associations</li>
  <li>Testing</li>
  <li>Security</li>
  <li>Deployment</li>
</ul>

<p>
  You can either sign up via email, or check out the sample account I've made.
  Just <%= link_to "log in", login_path %> as "account@example.com" with the password "password"!
</p>

<p>
  If you're a technical type, feel free to check out the source code.
</p>

<p>
  If you're any type at all, I'm happy to chat about all of the above and more.
</p>
<p>
  Feel free to send me an email at
  <%= mail_to "augustine.wittkower@gmail.com" %>
   if you have any questions!
</p>

app/views/static_pages/contact.html.erb
<%= provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  <b>Email: </b> <%= mail_to "augustine.wittkower@gmail.com", "augustine.wittkower@gmail.com" %>
</p>
<p>
  <b>Website: </b> <%= link_to "augustine.io", "http://augustine.io" %>
</p>
<p>
  <b>Github: </b> <%= link_to "github.com/augustine-", "http://github.com/augustine-" %>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Twiiter</h1>
<h2>How to use Twiiter</h2>
<ol>
  <li>Navigate to the <%= link_to "home", root_path %> page.</li>
  <li>Click "Sign up now!", and enter your information.
    (Passwords are stored as encrypted hashes in the database. Your secrets are safe with us!)</li>
  <li>Check your email for the activation link, follow it.</li>
  <li>Ta-da! You're ready to start following some users, or making some twiits of your own.</li>
  <li>You can change your password (with email confirmation) through the settings option in the top-right.</li>
</ol>

<p>
  <%= link_to "More questions?", contact_path %>
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <%= render 'feed' %>
<% else %>
  <%= render 'splash' %>
<% end %>